{
 "title": "Packets info",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Download upload speed test",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nc_download_speed", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Connection loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nc_connection_loss", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Total loss count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(nc_total_loss_packet_count[$__rate_interval])",
     "legendFormat": "loss rate"
    },
    { "expr": "nc_total_loss_packet_count", "legendFormat": "loss count" }
   ]
  },
  {
   "title": "Outage count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "nc_outage_count", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "RTT (avg,min,max)",
   "type": "timeseries",
   "description": "in ms",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "nc_avg_rtt", "legendFormat": "{{__name__}}" },
    { "expr": "nc_max_rtt", "legendFormat": "{{__name__}}" },
    { "expr": "nc_min_rtt", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "nc_latency / 1000000", "legendFormat": "Latency" }
   ]
  },
  {
   "title": "Device scan",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "ns_num_active_devices", "legendFormat": "__auto" }
   ]
  }
 ]
}